Repository PLADI-ALM/PLADI-ALM-Server, pull requests merged in 2023-12, with the labels that each got.

#264 [PDS-213/fix] 기획변경으로 인한 회원탈퇴 로직 수정
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/equipment/repository/EquipmentRepository.java
  src/main/java/com/example/pladialmserver/global/entityListener/UserEntityListener.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/product/car/repository/CarRepository.java
  src/main/java/com/example/pladialmserver/product/resource/repository/ResourceRepository.java
  src/main/java/com/example/pladialmserver/user/controller/AdminUserController.java
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: ⛑️ Fix

#266 [PDS-112/fix] 장비 및 차량 반납 시, 반납 시간으로 종료 시간 변경
  src/main/java/com/example/pladialmserver/booking/entity/CarBooking.java
  src/main/java/com/example/pladialmserver/booking/entity/ResourceBooking.java
  src/main/java/com/example/pladialmserver/booking/service/CarBookingService.java
  src/main/java/com/example/pladialmserver/booking/service/ResourceBookingService.java
Labels: ⛑️ Fix

#268 [PDS-197/fix] 해당 일시의 차량 예약 내역 조회 로직 수정
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingRepositoryImpl.java
Labels: ⛑️ Fix

#269 [PDS-56/feat] 비품 수정 API Req 수정
  src/main/java/com/example/pladialmserver/equipment/dto/request/UpdateEquipmentReq.java
Labels: 🔮 Feat

#273 [PDS-56/feat] 비품 정보 등록 API Req 수정
  src/main/java/com/example/pladialmserver/equipment/dto/request/RegisterEquipmentReq.java
Labels: 🔮 Feat

#275 [PDS-56/fix] 비품 수정 API Req 변경
  src/main/java/com/example/pladialmserver/equipment/dto/request/UpdateEquipmentReq.java
  src/test/java/com/example/pladialmserver/equipment/service/model/TestEquipmentInfo.java
Labels: 🔮 Feat

#276 [PDS-56/feat] git action firebase_service_key.json 등록
  .github/workflows/github-action.yml
Labels: 🎡 Infra

#277 [PDS-56/feat] git action firebase dir 생성
  .github/workflows/github-action.yml
Labels: 🎡 Infra

#278 [PDS-56/feat] notification message body 수정
  src/main/java/com/example/pladialmserver/notification/service/PushNotificationService.java
Labels: 🔮 Feat

#279 [PDS-56/feat] firebase API URL 변경
  src/main/java/com/example/pladialmserver/notification/service/PushNotificationService.java
Labels: 🔮 Feat

#282 [PDS-164/feat] 차량 관련 알림 수정
  src/main/java/com/example/pladialmserver/booking/service/CarBookingService.java
Labels: 🔮 Feat

#283 [PDS-116/fix] 관리자 장비 추가 로직 수정
  src/main/java/com/example/pladialmserver/product/resource/entity/Resource.java
Labels: ⛑️ Fix
