Repository PLADI-ALM/PLADI-ALM-Server, pull requests merged in 2023-09, with the labels that each got.

#6 [PDS-13/feat] 회의실 개별 조회 API구현
  src/main/java/com/example/pladialmserver/office/controller/OfficeController.java
  src/main/java/com/example/pladialmserver/office/dto/response/OfficeRes.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeBookingRepository.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeRepository.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: 🔮 Feat

#8 [PDS-14/feat] 회의실 예약 API
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/global/user/repository/UserRepository.java
  src/main/java/com/example/pladialmserver/office/controller/OfficeController.java
  src/main/java/com/example/pladialmserver/office/dto/request/OfficeReq.java
  src/main/java/com/example/pladialmserver/office/entity/OfficeBooking.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeBookingRepository.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: 🔮 Feat

#9 [PDS-14/fix] 예약하기 API office 찾기 메소드 충돌 에러 해결
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: 🪧 HOTFIX

#10 [PDS-22/feat] 회의실 예약 개별 조회 API 생성
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
  src/main/java/com/example/pladialmserver/booking/dto/response/OfficeBookingDetailRes.java
  src/main/java/com/example/pladialmserver/booking/entity/OfficeBooking.java
  src/main/java/com/example/pladialmserver/booking/repository/OfficeBookingRepository.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
  src/main/java/com/example/pladialmserver/global/entity/BaseEntity.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/global/user/repository/UserRepository.java
  src/main/java/com/example/pladialmserver/office/controller/OfficeController.java
  src/main/java/com/example/pladialmserver/office/entity/Facility.java
  src/main/java/com/example/pladialmserver/office/entity/Office.java
  src/main/java/com/example/pladialmserver/office/entity/OfficeFacility.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
  src/main/java/com/example/pladialmserver/user/entity/User.java
  src/main/java/com/example/pladialmserver/user/repository/UserRepository.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: 🔮 Feat

#11 [feat/PDS-27] QueryDSL 설정 추가
  build.gradle
  src/main/java/com/example/pladialmserver/global/config/QuerydslConfig.java
Labels: 🎡 Infra

#12 [PDS-28/feat] 회의실 예약 취소 API
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
  src/main/java/com/example/pladialmserver/booking/entity/OfficeBooking.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
Labels: 🔮 Feat

#13 [PDS-33/infra] CORS 설정
  src/main/java/com/example/pladialmserver/global/config/WebConfig.java
Labels: 🎡 Infra

#14 [PDS-20] 예약 목록 조회 API
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
  src/main/java/com/example/pladialmserver/booking/dto/response/BookingRes.java
  src/main/java/com/example/pladialmserver/booking/repository/OfficeBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/OfficeBookingRepository.java
  src/main/java/com/example/pladialmserver/booking/repository/OfficeBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
  src/main/java/com/example/pladialmserver/global/Constants.java
Labels: 🔮 Feat

#15 [PDS-26] 스웨거 설정
  build.gradle
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
  src/main/java/com/example/pladialmserver/global/CustomPage.java
  src/main/java/com/example/pladialmserver/global/config/SwaggerConfig.java
  src/main/java/com/example/pladialmserver/global/controller/TestController.java
  src/main/java/com/example/pladialmserver/office/controller/OfficeController.java
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
  src/main/resources/application.properties
Labels: 🔮 Feat

#16 [PDS-30/feat] 회의실 목록조회 페이징 처리
  src/main/java/com/example/pladialmserver/booking/repository/OfficeBookingRepository.java
  src/main/java/com/example/pladialmserver/office/controller/OfficeController.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeRepository.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: 🔮 Feat

#17 [PDS-31/feat] Aws S3 콘텐츠 업로드를 위한 util 설정 및 yml 설정
  src/main/java/com/example/pladialmserver/global/utils/AwsS3ImageUrlUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: 🔮 Feat

#18 [PDS-14/feat] 회의실 예약 API QueryDsl 변경 및 회의실예약/회의실 예약 취소 API 스웨거 설정
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
  src/main/java/com/example/pladialmserver/booking/repository/OfficeBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/OfficeBookingRepository.java
  src/main/java/com/example/pladialmserver/booking/repository/OfficeBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/global/config/SwaggerConfig.java
  src/main/java/com/example/pladialmserver/office/controller/OfficeController.java
  src/main/java/com/example/pladialmserver/office/dto/request/OfficeReq.java
Labels: 🔮 Feat

#20 [PDS-11] 예약된 회의실 제외한 회의실 목록조회 로직 수정
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: ⛑️ Fix

#21 [PDS-41/fix] update github-action.yml
  .github/workflows/github-action.yml
Labels: ⚓️ CI/CD, ⛑️ Fix, 🪧 HOTFIX

#22 [PDS-11] response에 id추가
  src/main/java/com/example/pladialmserver/office/dto/response/OfficeRes.java
Labels: ⛑️ Fix

#23 [PDS-15] 24:00 예외 처리 MIDNIGHT 가능하도록 변경
  src/main/java/com/example/pladialmserver/office/controller/OfficeController.java
Labels: 🪧 HOTFIX

#24 [PDS-99/feat] 회의실 예약 상태 변경 스케줄링
  src/main/java/com/example/pladialmserver/PladiAlmServerApplication.java
  src/main/java/com/example/pladialmserver/booking/entity/OfficeBooking.java
  src/main/java/com/example/pladialmserver/booking/repository/OfficeBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/OfficeBookingRepository.java
  src/main/java/com/example/pladialmserver/booking/repository/OfficeBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
Labels: 🔮 Feat
