Repository PLADI-ALM/PLADI-ALM-Server, pull requests merged in 2023-11, with the labels that each got.

#147 [PDS-157/feat] 관리자 회의실 목록 조회 api
  src/main/java/com/example/pladialmserver/office/controller/OfficeAdminController.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeRepository.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: 🔮 Feat, 🪧 HOTFIX

#148 [PDS-157/hotfix] 관리자 회의실 목록 조회 api수정
  src/main/java/com/example/pladialmserver/office/controller/OfficeAdminController.java
  src/main/java/com/example/pladialmserver/office/dto/response/OfficeRes.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: 🪧 HOTFIX

#149 [PDS-153/feat] 차량 예약 API
  src/main/java/com/example/pladialmserver/booking/entity/CarBooking.java
  src/main/java/com/example/pladialmserver/booking/entity/ResourceBooking.java
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/product/car/controller/CarController.java
  src/main/java/com/example/pladialmserver/product/car/service/CarService.java
  src/main/java/com/example/pladialmserver/product/dto/request/ProductReq.java
  src/main/java/com/example/pladialmserver/product/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/product/resource/service/ResourceService.java
  src/main/java/com/example/pladialmserver/product/service/ProductService.java
Labels: 🔮 Feat, 🧵 Refactor

#151 [PDS-155/feat] 차량 월별 예약 현황 조회 API
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/product/car/controller/CarController.java
  src/main/java/com/example/pladialmserver/product/car/service/CarService.java
  src/main/java/com/example/pladialmserver/product/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/product/resource/service/ResourceService.java
  src/main/java/com/example/pladialmserver/product/service/ProductService.java
Labels: 🔮 Feat, 🧵 Refactor

#152 [PDS-160/feat] 회의실 예약자 정보 확인 API
  src/main/java/com/example/pladialmserver/booking/repository/officeBooking/OfficeBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/officeBooking/OfficeBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/office/controller/OfficeController.java
  src/main/java/com/example/pladialmserver/office/dto/response/OfficeReservatorRes.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: 🔮 Feat

#155 [PDS-126/fix] 장비 및 차량 예약 상태 변경 스케줄링 datetime 기준으로 변경
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingRepository.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepository.java
  src/main/java/com/example/pladialmserver/booking/service/CarBookingService.java
  src/main/java/com/example/pladialmserver/booking/service/ResourceBookingService.java
Labels: ⛑️ Fix

#156 [PDS-103/fix] 장비 및 차량 예약 날짜 여부 확인 dateTime으로 변경
  src/main/java/com/example/pladialmserver/booking/dto/response/AdminBookingRes.java
  src/main/java/com/example/pladialmserver/booking/service/CarBookingService.java
  src/main/java/com/example/pladialmserver/booking/service/ResourceBookingService.java
  src/main/java/com/example/pladialmserver/office/dto/response/OfficesList.java
  src/main/java/com/example/pladialmserver/product/resource/dto/response/AdminProductRes.java
  src/main/java/com/example/pladialmserver/product/resource/dto/response/ResourcesList.java
Labels: ⛑️ Fix

#158 [PDS-163] 회의실, 장비, 자동차 예약에 관련된 알림 구현
  .gitignore
  build.gradle
  src/main/java/com/example/pladialmserver/booking/service/CarBookingService.java
  src/main/java/com/example/pladialmserver/booking/service/OfficeBookingService.java
  src/main/java/com/example/pladialmserver/booking/service/ResourceBookingService.java
  src/main/java/com/example/pladialmserver/global/Constants.java
  src/main/java/com/example/pladialmserver/notification/dto/FcmMessage.java
  src/main/java/com/example/pladialmserver/notification/dto/Message.java
  src/main/java/com/example/pladialmserver/notification/dto/Notification.java
  src/main/java/com/example/pladialmserver/notification/entity/PushNotification.java
  src/main/java/com/example/pladialmserver/notification/repository/PushNotificationRepository.java
  src/main/java/com/example/pladialmserver/notification/service/PushNotificationService.java
  src/main/java/com/example/pladialmserver/product/car/service/CarService.java
  src/main/java/com/example/pladialmserver/user/dto/request/CreateUserReq.java
  src/main/java/com/example/pladialmserver/user/entity/User.java
Labels: 🔮 Feat

#159 [PDS-161/refactor&feat] 모든 이메일 알림 구현
  src/main/java/com/example/pladialmserver/booking/dto/request/SendEmailReq.java
  src/main/java/com/example/pladialmserver/booking/service/CarBookingService.java
  src/main/java/com/example/pladialmserver/booking/service/OfficeBookingService.java
  src/main/java/com/example/pladialmserver/booking/service/ResourceBookingService.java
  src/main/java/com/example/pladialmserver/global/Constants.java
  src/main/java/com/example/pladialmserver/global/utils/EmailUtil.java
  src/main/java/com/example/pladialmserver/product/car/service/CarService.java
  src/main/java/com/example/pladialmserver/product/resource/service/ResourceService.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
  src/main/resources/templates/booking.html
Labels: ⛑️ Fix, 🔮 Feat, 🧵 Refactor

#162 [PDS-99/fix] 회의실 종료 스케줄링 코드 수정
  src/main/java/com/example/pladialmserver/booking/repository/officeBooking/OfficeBookingRepositoryImpl.java
Labels: ⛑️ Fix

#163 [PDS-159/fix] 클라이언트에서 이미지 key로 받는게 아니라 url로 받도록 수정
  src/main/java/com/example/pladialmserver/product/resource/dto/response/ResourceRes.java
Labels: ⛑️ Fix

#164 [PDS-2/fix] 회의실 목록조회 시설 이름 contain함수 적용, 회의실 사용중이면 조회 안되도록 수정
  src/main/java/com/example/pladialmserver/booking/repository/officeBooking/OfficeBookingRepository.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeRepository.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: ⛑️ Fix

#160 [PDS-169/feat] 직원 등록 API feign client 적용
  src/main/java/com/example/pladialmserver/global/feign/dto/UserReq.java
  src/main/java/com/example/pladialmserver/global/feign/event/UserEvent.java
  src/main/java/com/example/pladialmserver/global/feign/publisher/ArchivingServerEventPublisher.java
  src/main/java/com/example/pladialmserver/global/feign/publisher/ArchivingServerEventPublisherImpl.java
  src/main/java/com/example/pladialmserver/user/dto/request/CreateUserReq.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
  src/main/resources/application-dev.yml
Labels: 🔮 Feat

#165 [PDS-170/feat] 아카이빙 유저 정보전달 EventPubliser 구현
  src/main/java/com/example/pladialmserver/global/feign/dto/UserReq.java
  src/main/java/com/example/pladialmserver/global/feign/event/UpdateUserEvent.java
  src/main/java/com/example/pladialmserver/global/feign/event/UserEvent.java
  src/main/java/com/example/pladialmserver/global/feign/feignClient/ArchivingServerClient.java
  src/main/java/com/example/pladialmserver/global/feign/handler/ArchivingServerEventHandler.java
  src/main/java/com/example/pladialmserver/global/feign/handler/ArchivingServerEventHandlerImpl.java
Labels: 🔮 Feat

#166 [PDS-157/fix] 관리자 회의실 목록 조회 contain함수로 수정, 스웨거 response 기획에 맞게 수정
  src/main/java/com/example/pladialmserver/office/controller/OfficeAdminController.java
  src/main/java/com/example/pladialmserver/office/dto/response/AdminOfficeRes.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeRepository.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: ⛑️ Fix

#167 [PDS-83/fix] 사용자 정보 역할 정보 추가
  src/main/java/com/example/pladialmserver/user/dto/response/UserNameRes.java
Labels: ⛑️ Fix

#168 [PDS-163/feat] 푸쉬 알림 타이틀 로직 변경 및 유저 알림 목록조회 API 기능구현
  src/main/java/com/example/pladialmserver/booking/service/CarBookingService.java
  src/main/java/com/example/pladialmserver/booking/service/OfficeBookingService.java
  src/main/java/com/example/pladialmserver/booking/service/ResourceBookingService.java
  src/main/java/com/example/pladialmserver/global/Constants.java
  src/main/java/com/example/pladialmserver/notification/entity/PushNotification.java
  src/main/java/com/example/pladialmserver/notification/repository/PushNotificationRepository.java
  src/main/java/com/example/pladialmserver/notification/service/PushNotificationService.java
  src/main/java/com/example/pladialmserver/product/car/service/CarService.java
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
  src/main/java/com/example/pladialmserver/user/dto/response/NotificationRes.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: 🔮 Feat

#169 [PDS-161/fix] 이메일 전송 디테일한 디자인 html 수정
  src/main/java/com/example/pladialmserver/office/controller/OfficeController.java
  src/main/resources/templates/booking.html
  src/main/resources/templates/email.html
Labels: ⛑️ Fix

#170 [PDS-147/refactor] 차량 목록 조회 jpql에서 query dsl로 리펙토링
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/product/car/controller/CarController.java
  src/main/java/com/example/pladialmserver/product/car/repository/CarCustom.java
  src/main/java/com/example/pladialmserver/product/car/repository/CarRepositoryImpl.java
  src/main/java/com/example/pladialmserver/product/car/service/CarService.java
Labels: ⛑️ Fix, 🧵 Refactor

#171 [PDS-163/feat] 유저 알림 목록 조회 API response swagger 설정
  src/main/java/com/example/pladialmserver/user/dto/response/NotificationRes.java
Labels: 🔮 Feat

#172 [PDS-163/feat] 유저 알림 목록 조회 API 리턴타입 명시
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
Labels: 🔮 Feat

#173 [PDS-147/hotfix] respository -> respository 주입이 아니라 서비스 로직으로 추출
  src/main/java/com/example/pladialmserver/product/car/repository/CarCustom.java
  src/main/java/com/example/pladialmserver/product/car/repository/CarRepositoryImpl.java
  src/main/java/com/example/pladialmserver/product/car/service/CarService.java
Labels: 🪧 HOTFIX

#175 [PDS-147/hotfix] 차랑 목록 조회 resposnse AwsS3ImageUrlUtil로 변경
  src/main/java/com/example/pladialmserver/product/car/dto/CarRes.java
Labels: 🪧 HOTFIX

#176 [PDS-163/hotfix] 직원 등록 시, fcmToken req 삭제
  src/main/java/com/example/pladialmserver/user/dto/request/CreateUserReq.java
  src/main/java/com/example/pladialmserver/user/entity/User.java
Labels: 🪧 HOTFIX

#174 [PDS-2/fix] 지난 날짜와 입력시 예외처리, 시작시간이 끝나는 시간보다 빠르면 예외처리
  src/main/java/com/example/pladialmserver/office/controller/OfficeController.java
Labels: ⛑️ Fix

#177 [PDS-171/infra] 테스트 코드 초기설정 구축
  build.gradle
  src/test/java/com/example/pladialmserver/global/ControllerTestSupport.java
  src/test/java/com/example/pladialmserver/global/IntegrationTestSupport.java
  src/test/java/com/example/pladialmserver/infra/HealthCheckControllerTest.java
  src/test/java/com/example/pladialmserver/office/controller/OfficeControllerTest.java
  src/test/java/com/example/pladialmserver/office/service/OfficeServiceTest.java
  src/test/java/com/example/pladialmserver/resource/controller/ResourceControllerTest.java
  src/test/java/com/example/pladialmserver/resource/service/ResourceServiceTest.java
  src/test/resources/application.yaml
Labels: 🎡 Infra

#179 [PDS-70/fix] 장비&차량 비활성화 상태에서도 조회 가능하도록 설정
  src/main/java/com/example/pladialmserver/product/car/repository/CarRepository.java
  src/main/java/com/example/pladialmserver/product/car/service/CarService.java
  src/main/java/com/example/pladialmserver/product/resource/repository/ResourceRepository.java
  src/main/java/com/example/pladialmserver/product/resource/service/ResourceService.java
Labels: ⛑️ Fix

#180 [PDS-76/fix] 장비 및 차량 반납 기타사항 추가, 반납장소 업데이트, 권한 수정
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
  src/main/java/com/example/pladialmserver/booking/controller/CarBookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/controller/ResourceBookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/dto/request/ReturnProductReq.java
  src/main/java/com/example/pladialmserver/booking/entity/CarBooking.java
  src/main/java/com/example/pladialmserver/booking/entity/OfficeBooking.java
  src/main/java/com/example/pladialmserver/booking/entity/ResourceBooking.java
  src/main/java/com/example/pladialmserver/booking/service/CarBookingService.java
  src/main/java/com/example/pladialmserver/booking/service/ProductBookingService.java
  src/main/java/com/example/pladialmserver/booking/service/ResourceBookingService.java
  src/main/java/com/example/pladialmserver/product/car/entity/Car.java
  src/main/java/com/example/pladialmserver/product/resource/entity/Resource.java
Labels: ⛑️ Fix

#182 [PDS-149/fix] 장비 및 차량 일시 기준 예약 현황 조회
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/product/car/controller/CarController.java
  src/main/java/com/example/pladialmserver/product/car/service/CarService.java
  src/main/java/com/example/pladialmserver/product/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/product/resource/service/ResourceService.java
  src/main/java/com/example/pladialmserver/product/service/ProductService.java
Labels: ⛑️ Fix

#181 [PDS-168/fix] 차량 예약 허가 삭제
  src/main/java/com/example/pladialmserver/booking/controller/CarBookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/entity/CarBooking.java
  src/main/java/com/example/pladialmserver/booking/service/CarBookingService.java
  src/main/java/com/example/pladialmserver/booking/service/ProductBookingService.java
  src/main/java/com/example/pladialmserver/booking/service/ResourceBookingService.java
Labels: ⛑️ Fix

#183 [PDS-168/hotfix] 충돌 해결
  src/main/java/com/example/pladialmserver/booking/service/ProductBookingService.java
Labels: 🪧 HOTFIX

#184 [PDS-123/fix] 직원 컬럼 자산(컴퓨터)정보 추가
  src/main/java/com/example/pladialmserver/user/dto/request/CreateUserReq.java
  src/main/java/com/example/pladialmserver/user/dto/request/UpdateUserReq.java
  src/main/java/com/example/pladialmserver/user/dto/response/UserRes.java
  src/main/java/com/example/pladialmserver/user/entity/User.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: ⛑️ Fix

#188 [PDS-176/refactor] 비품 관리 권한 수정 및 워딩 변경
  src/main/java/com/example/pladialmserver/equipment/dto/request/UpdateEquipmentReq.java
  src/main/java/com/example/pladialmserver/equipment/service/EquipmentService.java
Labels: 🧵 Refactor

#190 [PDS-178/refactor] 예약 내역 관련 알림 수신자 변경
  src/main/java/com/example/pladialmserver/booking/service/ResourceBookingService.java
  src/main/java/com/example/pladialmserver/product/car/service/CarService.java
Labels: 🧵 Refactor

#187 [PDS-96/fix] 직원 계정 목록 조회 부서 추가
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/user/controller/AdminUserController.java
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
  src/main/java/com/example/pladialmserver/user/dto/request/AdminUpdateUserReq.java
  src/main/java/com/example/pladialmserver/user/dto/request/CreateUserReq.java
  src/main/java/com/example/pladialmserver/user/dto/request/UpdateUserReq.java
  src/main/java/com/example/pladialmserver/user/dto/response/UserRes.java
  src/main/java/com/example/pladialmserver/user/entity/Affiliation.java
  src/main/java/com/example/pladialmserver/user/entity/User.java
  src/main/java/com/example/pladialmserver/user/repository/AffiliationRepository.java
  src/main/java/com/example/pladialmserver/user/repository/user/UserCustom.java
  src/main/java/com/example/pladialmserver/user/repository/user/UserRepositoryImpl.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: ⛑️ Fix, 🔮 Feat

#192 [PDS-168/refactor] 공통 dto 사용으로 인한 컬럼 네이밍 변경, 조회 쿼리문 수정
  src/main/java/com/example/pladialmserver/booking/dto/response/BookingRes.java
  src/main/java/com/example/pladialmserver/booking/dto/response/ProductBookingDetailRes.java
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingRepositoryImpl.java
Labels: ⛑️ Fix, 🧵 Refactor

#189 [PDS-149/refactor] 비품 수량 정보 변경 (Integer -> String)
  src/main/java/com/example/pladialmserver/equipment/dto/request/RegisterEquipmentReq.java
  src/main/java/com/example/pladialmserver/equipment/dto/request/UpdateEquipmentReq.java
  src/main/java/com/example/pladialmserver/equipment/dto/response/SearchEquipmentRes.java
  src/main/java/com/example/pladialmserver/equipment/entity/Equipment.java
Labels: 🧵 Refactor

#178 [PDS-116/feat] 장비&차량 제조사 컬럼 추가
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/product/car/dto/CarRes.java
  src/main/java/com/example/pladialmserver/product/car/entity/Car.java
  src/main/java/com/example/pladialmserver/product/car/repository/CarRepositoryImpl.java
  src/main/java/com/example/pladialmserver/product/dto/response/ProductDetailRes.java
  src/main/java/com/example/pladialmserver/product/resource/controller/ResourceAdminController.java
  src/main/java/com/example/pladialmserver/product/resource/dto/request/CreateResourceReq.java
  src/main/java/com/example/pladialmserver/product/resource/dto/response/AdminResourcesRes.java
  src/main/java/com/example/pladialmserver/product/resource/dto/response/ResourceRes.java
  src/main/java/com/example/pladialmserver/product/resource/entity/Resource.java
  src/main/java/com/example/pladialmserver/product/resource/repository/ResourceRepositoryImpl.java
Labels: 🔮 Feat

#193 충돌 해결
  src/main/java/com/example/pladialmserver/equipment/dto/request/UpdateEquipmentReq.java
Labels: 🪧 HOTFIX

#194 [PDS-161/fix] 예약 취소 이메일 전송 추가
  src/main/java/com/example/pladialmserver/booking/service/CarBookingService.java
  src/main/java/com/example/pladialmserver/booking/service/OfficeBookingService.java
  src/main/java/com/example/pladialmserver/booking/service/ResourceBookingService.java
  src/main/java/com/example/pladialmserver/global/Constants.java
Labels: ⛑️ Fix

#195 [PDS-2/hotfix] 회의실 목록조회 수정
  src/main/java/com/example/pladialmserver/booking/repository/officeBooking/OfficeBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/officeBooking/OfficeBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/office/controller/OfficeController.java
  src/main/java/com/example/pladialmserver/office/dto/response/OfficeRes.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeCustom.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeRepository.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeRepositoryImpl.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: 🪧 HOTFIX

#197 [PDS-20/fix] 예약 목록 조회 이용목적 추가
  src/main/java/com/example/pladialmserver/booking/dto/response/BookingRes.java
Labels: ⛑️ Fix

#198 [PDS-71/hotfix] 장비 및 차량 월별 예약 현황 조회 시, null처리
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepositoryImpl.java
Labels: 🪧 HOTFIX

#196 [PDS-180/fix] 회의실 수용인원 타입 수정
  src/main/java/com/example/pladialmserver/office/dto/response/AdminOfficeRes.java
  src/main/java/com/example/pladialmserver/office/dto/response/AdminOfficesDetailsRes.java
  src/main/java/com/example/pladialmserver/office/dto/response/OfficeRes.java
  src/main/java/com/example/pladialmserver/office/entity/Office.java
  src/main/java/com/example/pladialmserver/product/resource/dto/request/CreateOfficeReq.java
Labels: ⛑️ Fix

#199 [PDS-88/fix] 자원 목록 조회 이미 지난 날짜 예약 조회 x, 시작시간이 끝나는시간보다 느리게 조회 x
  src/main/java/com/example/pladialmserver/product/resource/controller/ResourceController.java
Labels: ⛑️ Fix

#200 [PDS-184/feat] 차량 예약 관리는 해당 차량 책임자가 관리 권한
  src/main/java/com/example/pladialmserver/product/car/controller/CarAdminController.java
  src/main/java/com/example/pladialmserver/product/car/entity/Car.java
  src/main/java/com/example/pladialmserver/product/car/service/CarService.java
  src/main/java/com/example/pladialmserver/user/entity/Role.java
Labels: 🔮 Feat

#202 [PDS-51/hotfix] 차량 예약 취소 Transactional Annotation 추가
  src/main/java/com/example/pladialmserver/booking/service/CarBookingService.java
Labels: 🪧 HOTFIX

#203 [PDS-184/hotfix] 차량 예약 관리 접근관한 변경
  src/main/java/com/example/pladialmserver/product/car/service/CarService.java
  src/main/java/com/example/pladialmserver/user/entity/Role.java
Labels: 🪧 HOTFIX

#204 [PDS-188] hotfix: 장비/차량 목록 조회 id로 통일
  src/main/java/com/example/pladialmserver/product/resource/dto/response/AdminResourcesRes.java
Labels: 🪧 HOTFIX

#206 [PDS-189/feat] user asserts -> assets 변경 & notification controller 생성
  src/main/java/com/example/pladialmserver/global/Constants.java
  src/main/java/com/example/pladialmserver/notification/controller/NotificationController.java
  src/main/java/com/example/pladialmserver/notification/service/PushNotificationService.java
  src/main/java/com/example/pladialmserver/user/dto/request/AdminUpdateUserReq.java
  src/main/java/com/example/pladialmserver/user/dto/request/CreateUserReq.java
  src/main/java/com/example/pladialmserver/user/dto/request/UpdateUserReq.java
  src/main/java/com/example/pladialmserver/user/dto/response/UserRes.java
  src/main/java/com/example/pladialmserver/user/entity/User.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: 🔮 Feat

#205 [PDS-161/feat] 자원 / 차량 반납 이메일 특이사항 전송
  src/main/java/com/example/pladialmserver/booking/dto/request/ReturnProductReq.java
  src/main/java/com/example/pladialmserver/booking/dto/request/SendEmailReq.java
  src/main/java/com/example/pladialmserver/global/Constants.java
  src/main/java/com/example/pladialmserver/global/utils/EmailUtil.java
  src/main/resources/templates/booking.html
Labels: 🔮 Feat

#207 [PDS-190/feat] 자산 정보 확인 요청 이메일 전송
  src/main/java/com/example/pladialmserver/global/Constants.java
  src/main/java/com/example/pladialmserver/global/utils/EmailUtil.java
  src/main/java/com/example/pladialmserver/user/dto/request/SendAssetsEmailReq.java
  src/main/java/com/example/pladialmserver/user/repository/user/UserRepository.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
  src/main/resources/templates/assets.html
Labels: 🔮 Feat

#208 [PDS-171/feat] 회의실 목록 조회 성공 테스트 코드 작성
  build.gradle
  src/main/java/com/example/pladialmserver/office/entity/Facility.java
  src/main/java/com/example/pladialmserver/user/entity/Affiliation.java
  src/main/java/com/example/pladialmserver/user/entity/Department.java
  src/main/java/com/example/pladialmserver/user/entity/User.java
  src/test/java/com/example/pladialmserver/global/ControllerTestSupport.java
  src/test/java/com/example/pladialmserver/office/controller/OfficeControllerTest.java
  src/test/java/com/example/pladialmserver/office/service/OfficeServiceTest.java
  src/test/resources/application.yaml
Labels: 📝 Test

#209 [PDS-171/hotfix] user엔티티 테이블 이름 변경
  src/main/java/com/example/pladialmserver/user/entity/User.java
Labels: 🪧 HOTFIX

#210 hotfix : user 엔티티 sqlDetele맞게 수정
  src/main/java/com/example/pladialmserver/user/entity/User.java
Labels: 🪧 HOTFIX

#211 [PDS-190/fix] 자산 정보 확인 요청 이메일 전송 소속, 부서명 삭제
  src/main/java/com/example/pladialmserver/global/utils/EmailUtil.java
  src/main/java/com/example/pladialmserver/user/dto/request/SendAssetsEmailReq.java
  src/main/resources/templates/assets.html
Labels: ⛑️ Fix

#214 [PDS-192/infra] sonarCloud 초기설정
  .github/workflows/sonarCloud.yaml
  build.gradle
Labels: 🎡 Infra

#213 [PDS-191/feat] 로그인시 fcm 토큰 할당
  src/main/java/com/example/pladialmserver/user/dto/request/EmailPWReq.java
  src/main/java/com/example/pladialmserver/user/entity/User.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: 🔮 Feat

#215 [PDS-112/fix] 장비 및 차량 예약 반납 request 및 uri 수정
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
  src/main/java/com/example/pladialmserver/booking/controller/CarBookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/controller/ResourceBookingAdminController.java
Labels: ⛑️ Fix

#217 [PDS-71/hotfix] 장비 및 차량 월별 예약 조회 로직 수정
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepositoryImpl.java
Labels: 🪧 HOTFIX

#218 [PDS-194/feat] 해당 날짜의 장비/차량 예약된 시간 조회
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/global/utils/DateTimeUtil.java
  src/main/java/com/example/pladialmserver/product/car/controller/CarController.java
  src/main/java/com/example/pladialmserver/product/car/service/CarService.java
  src/main/java/com/example/pladialmserver/product/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/product/resource/service/ResourceService.java
  src/main/java/com/example/pladialmserver/product/service/ProductService.java
Labels: 🔮 Feat

#219 [PDS-194/fix] 장비 및 차량 월별 예약 현황 조회 미사용 로직 삭제
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/product/car/controller/CarController.java
  src/main/java/com/example/pladialmserver/product/car/service/CarService.java
  src/main/java/com/example/pladialmserver/product/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/product/resource/service/ResourceService.java
  src/main/java/com/example/pladialmserver/product/service/ProductService.java
Labels: ⛑️ Fix

#221 [PDS-192/fix] 소나 클라우드 암호화 설정 추가
  .github/workflows/sonarCloud.yaml
Labels: ⛑️ Fix, 🎡 Infra

#224 [PDS-167/feat] 관리자 차량 API 구현 및 장비와 표준화
  src/main/java/com/example/pladialmserver/booking/controller/car/CarBookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/controller/resource/ResourceBookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingRepository.java
  src/main/java/com/example/pladialmserver/booking/service/CarBookingService.java
  src/main/java/com/example/pladialmserver/booking/service/ProductBookingService.java
  src/main/java/com/example/pladialmserver/booking/service/ResourceBookingService.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/office/controller/OfficeAdminController.java
  src/main/java/com/example/pladialmserver/office/dto/request/CreateOfficeReq.java
  src/main/java/com/example/pladialmserver/office/entity/Office.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
  src/main/java/com/example/pladialmserver/product/car/controller/CarAdminController.java
  src/main/java/com/example/pladialmserver/product/car/controller/CarController.java
  src/main/java/com/example/pladialmserver/product/car/entity/Car.java
  src/main/java/com/example/pladialmserver/product/car/repository/CarCustom.java
  src/main/java/com/example/pladialmserver/product/car/repository/CarRepositoryImpl.java
  src/main/java/com/example/pladialmserver/product/car/service/CarService.java
  src/main/java/com/example/pladialmserver/product/dto/request/CreateProductReq.java
  src/main/java/com/example/pladialmserver/product/dto/response/AdminProductDetailsRes.java
  src/main/java/com/example/pladialmserver/product/dto/response/AdminProductRes.java
  src/main/java/com/example/pladialmserver/product/dto/response/AdminProductsRes.java
  src/main/java/com/example/pladialmserver/product/dto/response/ProductList.java
  src/main/java/com/example/pladialmserver/product/resource/controller/ResourceAdminController.java
  src/main/java/com/example/pladialmserver/product/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/product/resource/dto/ResourceRes.java
  src/main/java/com/example/pladialmserver/product/resource/dto/request/CreateResourceReq.java
  src/main/java/com/example/pladialmserver/product/resource/dto/response/AdminResourcesDetailsRes.java
  src/main/java/com/example/pladialmserver/product/resource/entity/Resource.java
  src/main/java/com/example/pladialmserver/product/resource/repository/ResourceCustom.java
  src/main/java/com/example/pladialmserver/product/resource/repository/ResourceRepositoryImpl.java
  src/main/java/com/example/pladialmserver/product/resource/service/ResourceService.java
  src/main/java/com/example/pladialmserver/product/service/ProductService.java
Labels: 🔮 Feat

#212 [PDS-189/feat] 자산 정보 확인 요청 알림 구현
  src/main/java/com/example/pladialmserver/global/Constants.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/notification/controller/NotificationController.java
  src/main/java/com/example/pladialmserver/notification/service/PushNotificationService.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: 🔮 Feat

#222 [PDS-81/test] 로그인 API 성공 단위 테스트
  src/main/java/com/example/pladialmserver/user/dto/TokenDto.java
  src/main/java/com/example/pladialmserver/user/dto/request/EmailPWReq.java
  src/main/java/com/example/pladialmserver/user/entity/User.java
  src/test/java/com/example/pladialmserver/user/service/UserServiceTest.java
  src/test/java/com/example/pladialmserver/user/service/model/TestUserInfo.java
Labels: 📝 Test

#223 [PDS-192/hotfix] sonarCloud ci 수정
  .github/workflows/sonarCloud.yaml
  build.gradle
Labels: ⛑️ Fix, 🎡 Infra

#225 [PDS-195/test] 구매 장비 등록 API 성공 테스트 구현
  src/main/java/com/example/pladialmserver/equipment/dto/request/RegisterEquipmentReq.java
  src/test/java/com/example/pladialmserver/equipment/controller/EquipmentControllerTest.java
  src/test/java/com/example/pladialmserver/equipment/service/EquipmentServiceTest.java
  src/test/java/com/example/pladialmserver/equipment/service/model/TestEquipmentInfo.java
Labels: 📝 Test

#226 [PDS-196/test] 장비 예약 개별 조회 API 성공&실패 테스트 구현
  src/main/java/com/example/pladialmserver/booking/entity/ResourceBooking.java
  src/main/java/com/example/pladialmserver/product/resource/entity/Resource.java
  src/main/java/com/example/pladialmserver/user/entity/User.java
  src/test/java/com/example/pladialmserver/booking/service/ResourceBookingServiceTest.java
  src/test/java/com/example/pladialmserver/booking/service/model/TestResourceBookingInfo.java
  src/test/java/com/example/pladialmserver/resource/service/model/TestResourceInfo.java
  src/test/java/com/example/pladialmserver/user/service/model/TestUserInfo.java
Labels: 📝 Test

#227 [PDS-197/feat] 해당 날짜의 예약된 정보 조회 API
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/product/car/controller/CarController.java
  src/main/java/com/example/pladialmserver/product/car/service/CarService.java
  src/main/java/com/example/pladialmserver/product/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/product/resource/service/ResourceService.java
  src/main/java/com/example/pladialmserver/product/service/ProductService.java
Labels: 🔮 Feat

#228 [PDS-171/test] 회의실 목록조회 실패 case 테스트 코드 구현
  src/test/java/com/example/pladialmserver/office/controller/OfficeControllerTest.java
  src/test/java/com/example/pladialmserver/office/service/OfficeServiceTest.java
Labels: 📝 Test

#229 [PDS-81/test] 로그인 실패 코드 작성
  src/main/java/com/example/pladialmserver/user/entity/User.java
  src/test/java/com/example/pladialmserver/booking/service/ResourceBookingServiceTest.java
  src/test/java/com/example/pladialmserver/equipment/service/EquipmentServiceTest.java
  src/test/java/com/example/pladialmserver/user/service/UserServiceTest.java
  src/test/java/com/example/pladialmserver/user/service/model/TestUserInfo.java
Labels: 📝 Test

#230 [PDS-198/test] 자원 목록 조회 성공, 실패case 테스트 코드 작성
  src/main/java/com/example/pladialmserver/product/resource/entity/Resource.java
  src/test/java/com/example/pladialmserver/office/service/OfficeServiceTest.java
  src/test/java/com/example/pladialmserver/resource/controller/ResourceControllerTest.java
  src/test/java/com/example/pladialmserver/resource/service/ResourceServiceTest.java
Labels: 📝 Test

#232 [PDS-81/hotfix] user builder id 추가
  src/main/java/com/example/pladialmserver/user/dto/request/EmailPWReq.java
  src/main/java/com/example/pladialmserver/user/entity/User.java
  src/test/java/com/example/pladialmserver/resource/service/ResourceServiceTest.java
  src/test/java/com/example/pladialmserver/user/service/model/TestUserInfo.java
Labels: 🪧 HOTFIX

#233 [PDS-116/fix] 장비 및 차량 추가 로직 수정
  src/main/java/com/example/pladialmserver/product/car/entity/Car.java
  src/main/java/com/example/pladialmserver/product/resource/entity/Resource.java
Labels: ⛑️ Fix

#236 [PDS-199/test] 비품 검색 조회 API 테스트
  src/test/java/com/example/pladialmserver/equipment/controller/EquipmentControllerTest.java
  src/test/java/com/example/pladialmserver/equipment/service/EquipmentServiceTest.java
  src/test/java/com/example/pladialmserver/equipment/service/model/TestEquipmentInfo.java
Labels: 📝 Test

#237 [PDS-15/test] 회의실 예약 성공 & 취소 테스트 코드
  src/main/java/com/example/pladialmserver/global/utils/DateTimeUtil.java
  src/main/java/com/example/pladialmserver/office/dto/request/OfficeReq.java
  src/main/java/com/example/pladialmserver/office/entity/Office.java
  src/test/java/com/example/pladialmserver/office/service/OfficeServiceBookingTest.java
  src/test/java/com/example/pladialmserver/office/service/model/TestOfficeInfo.java
Labels: 📝 Test

#238 [PDS-202/test] 비품 정보 수정 API 테스트
  src/main/java/com/example/pladialmserver/equipment/dto/request/UpdateEquipmentReq.java
  src/test/java/com/example/pladialmserver/equipment/service/EquipmentServiceTest.java
  src/test/java/com/example/pladialmserver/equipment/service/model/TestEquipmentInfo.java
Labels: 📝 Test

#240 [PDS-116/hotfix] Car builder 인자 수정
  src/main/java/com/example/pladialmserver/product/car/entity/Car.java
Labels: 🪧 HOTFIX

#242 [PDS-116/hotfix] 엔티티 수정 메서드 equals간 순서 변경
  src/main/java/com/example/pladialmserver/office/entity/Office.java
  src/main/java/com/example/pladialmserver/product/car/entity/Car.java
  src/main/java/com/example/pladialmserver/product/resource/entity/Resource.java
Labels: 🪧 HOTFIX

#239 [PDS-203/test] 비품 정보 삭제 API 테스트
  src/test/java/com/example/pladialmserver/equipment/service/EquipmentServiceTest.java
  src/test/java/com/example/pladialmserver/equipment/service/model/TestEquipmentInfo.java
Labels: 📝 Test

#247 [PDS-116/hotfix] 장비 및 차량 Builder.Default 설정
  src/main/java/com/example/pladialmserver/booking/entity/CarBooking.java
  src/main/java/com/example/pladialmserver/booking/entity/ResourceBooking.java
  src/main/java/com/example/pladialmserver/product/car/entity/Car.java
  src/main/java/com/example/pladialmserver/product/resource/entity/Resource.java
Labels: 🪧 HOTFIX

#249 [PDS-208/feat] 회의실 시설 검색 API + 스웨거 설정
  src/main/java/com/example/pladialmserver/office/controller/OfficeAdminController.java
  src/main/java/com/example/pladialmserver/office/dto/request/CreateOfficeReq.java
  src/main/java/com/example/pladialmserver/office/entity/Office.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeCustom.java
  src/main/java/com/example/pladialmserver/office/repository/facility/FacilityCustom.java
  src/main/java/com/example/pladialmserver/office/repository/facility/FacilityRepository.java
  src/main/java/com/example/pladialmserver/office/repository/facility/FacilityRepositoryImpl.java
  src/main/java/com/example/pladialmserver/office/repository/office/OfficeCustom.java
  src/main/java/com/example/pladialmserver/office/repository/office/OfficeRepository.java
  src/main/java/com/example/pladialmserver/office/repository/office/OfficeRepositoryImpl.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
  src/test/java/com/example/pladialmserver/office/service/OfficeServiceBookingTest.java
  src/test/java/com/example/pladialmserver/office/service/OfficeServiceTest.java
Labels: 🔮 Feat

#251 [PDS-85/hotfix] 관리자 회의실 추가 isActive처리
  src/main/java/com/example/pladialmserver/office/entity/Office.java
Labels: 🪧 HOTFIX

#253 [PDS-130/fix] 비밀번호 재설정 req 변경
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
  src/main/java/com/example/pladialmserver/user/dto/request/ResetPWReq.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: ⛑️ Fix

#241 [PDS-124/test] 직원 개별 정보/리스트 성공 & 취소 테스트 코드
  src/main/java/com/example/pladialmserver/user/entity/User.java
  src/test/java/com/example/pladialmserver/user/service/UserServiceTest.java
  src/test/java/com/example/pladialmserver/user/service/model/TestUserInfo.java
Labels: 📝 Test

#244 [PDS-205/feat] 비품 카테고리 조회 API 기능구현
  src/main/java/com/example/pladialmserver/equipment/controller/EquipmentController.java
  src/main/java/com/example/pladialmserver/equipment/dto/response/EquipmentCategoryRes.java
  src/main/java/com/example/pladialmserver/equipment/repository/EquipmentCategoryRepository.java
  src/main/java/com/example/pladialmserver/equipment/service/EquipmentService.java
Labels: 🔮 Feat

#250 [PDS-206/test] 관리자 회의실 활성화/비활성화 성공/실패 테스트 코드 작성
  src/test/java/com/example/pladialmserver/office/service/OfficeServiceTest.java
Labels: 📝 Test

#254 [PDS-85/feat] 관리자 시설 추가, 수정 로직 추가
  src/main/java/com/example/pladialmserver/office/entity/Facility.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: 🔮 Feat

#255 [PDS-171/hotfix] 회의실 목록조회 테스트 코드 수정
  src/test/java/com/example/pladialmserver/office/service/OfficeServiceTest.java
Labels: 📝 Test, 🪧 HOTFIX

#258 [PDS-2/hotfix] 회의실 목록 조회 예약 상태여도 조회 안되게 수정
  src/main/java/com/example/pladialmserver/booking/repository/officeBooking/OfficeBookingRepository.java
Labels: 🪧 HOTFIX

#260 [PDS-171/hotfix] 회의실, 자원 목록 조회 테스트 코드 request날짜 수정
  src/test/java/com/example/pladialmserver/global/ControllerTestSupport.java
  src/test/java/com/example/pladialmserver/infra/HealthCheckControllerTest.java
  src/test/java/com/example/pladialmserver/office/controller/OfficeControllerTest.java
  src/test/java/com/example/pladialmserver/resource/controller/ResourceControllerTest.java
Labels: 🪧 HOTFIX

#256 [PDS-205/feat] 장비 카테고리 목록 조회 API 리스폰스 수정
  src/main/java/com/example/pladialmserver/equipment/controller/EquipmentController.java
  src/main/java/com/example/pladialmserver/equipment/dto/response/EquipmentCategoryRes.java
  src/main/java/com/example/pladialmserver/equipment/service/EquipmentService.java
Labels: 🔮 Feat

#257 [PDS-164/feat] 장비 예약 알림 구현
  src/main/java/com/example/pladialmserver/booking/service/ResourceBookingService.java
  src/main/java/com/example/pladialmserver/global/Constants.java
  src/main/java/com/example/pladialmserver/notification/service/PushNotificationService.java
  src/main/java/com/example/pladialmserver/product/car/service/CarService.java
  src/main/java/com/example/pladialmserver/product/resource/service/ResourceService.java
  src/test/java/com/example/pladialmserver/booking/service/ResourceBookingServiceTest.java
Labels: 🔮 Feat

#261 [PDS-194/feat] 장비 및 차량 예약된 시간 가져오는 로직 수정
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepositoryImpl.java
  src/test/java/com/example/pladialmserver/booking/service/ResourceBookingServiceTest.java
  src/test/java/com/example/pladialmserver/booking/service/model/TestResourceBookingInfo.java
  src/test/java/com/example/pladialmserver/resource/service/ResourceServiceTest.java
Labels: ⛑️ Fix

#262 [PDS-56/feat] 비품 상세조회 API 기능구현
  src/main/java/com/example/pladialmserver/equipment/controller/EquipmentController.java
  src/main/java/com/example/pladialmserver/equipment/dto/response/GetEquipmentRes.java
  src/main/java/com/example/pladialmserver/equipment/service/EquipmentService.java
Labels: 🔮 Feat

#263 [PDS-56/feat] 비품 등록 ImgKey NotBlank 제거
  src/main/java/com/example/pladialmserver/equipment/dto/request/RegisterEquipmentReq.java
Labels: 🔮 Feat
