Repository PLADI-ALM/PLADI-ALM-Server, pull requests merged in 2023-10, with the labels that each got.

#25 [refactor/PDS-100] DateTimeUtil 생성 및 적용
  src/main/java/com/example/pladialmserver/booking/dto/response/BookingRes.java
  src/main/java/com/example/pladialmserver/booking/dto/response/OfficeBookingDetailRes.java
  src/main/java/com/example/pladialmserver/global/utils/DateTimeUtil.java
  src/main/java/com/example/pladialmserver/office/dto/response/BookedTimeRes.java
Labels: 🧵 Refactor

#26 [PDS-101/fix] bookingStatus 워딩 수정 및 상태 추가
  src/main/java/com/example/pladialmserver/global/entity/BookingStatus.java
Labels: ⛑️ Fix

#27 [PDS-12/feat] db 스키마 변경으로 인한 엔티티 생성 및 연관관계 수정
  src/main/java/com/example/pladialmserver/booking/entity/ResourceBooking.java
  src/main/java/com/example/pladialmserver/equipment/entity/Category.java
  src/main/java/com/example/pladialmserver/equipment/entity/Equipment.java
  src/main/java/com/example/pladialmserver/resouce/entity/Resource.java
  src/main/java/com/example/pladialmserver/user/entity/Department.java
  src/main/java/com/example/pladialmserver/user/entity/Position.java
  src/main/java/com/example/pladialmserver/user/entity/Role.java
  src/main/java/com/example/pladialmserver/user/entity/User.java
Labels: 🎡 Infra, 🔮 Feat

#30 [PDS-12/feat] user -> position, deaprtment 단방향 연관관계 설정
  src/main/java/com/example/pladialmserver/resouce/entity/Resource.java
  src/main/java/com/example/pladialmserver/user/entity/Department.java
  src/main/java/com/example/pladialmserver/user/entity/Position.java
Labels: 🎡 Infra, 🔮 Feat

#28 [PDS-99/feat] 회의실 예약 상태 변경 스케줄링 사용중 상태 추가
  src/main/java/com/example/pladialmserver/booking/entity/OfficeBooking.java
  src/main/java/com/example/pladialmserver/booking/repository/OfficeBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/OfficeBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
Labels: 🔮 Feat

#31 [PDS-15/hotfix] 회의실 예약 예외처리 에러 해결
  src/main/java/com/example/pladialmserver/office/dto/request/OfficeReq.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: 🪧 HOTFIX

#29 [PDS-22/docs] 회의실 예약 개별 조회 API Swagger 설정
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
  src/main/java/com/example/pladialmserver/booking/dto/response/OfficeBookingDetailRes.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
Labels: 📒 Docs

#33 Resource 도메인 틀생성
  src/main/java/com/example/pladialmserver/booking/repository/ResourceBookingRepository.java
  src/main/java/com/example/pladialmserver/resouce/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/resouce/dto/request/ResourceReq.java
  src/main/java/com/example/pladialmserver/resouce/dto/response/ResourceRes.java
  src/main/java/com/example/pladialmserver/resouce/repository/ResourceRepository.java
  src/main/java/com/example/pladialmserver/resouce/service/ResourceService.java
Labels: 🪧 HOTFIX

#34 [PDS-22/fix] 회의실 예약 개별 조회 회의실ID 추가
  src/main/java/com/example/pladialmserver/booking/dto/response/OfficeBookingDetailRes.java
Labels: ⛑️ Fix

#40 [PDS-22/hotfix] 생략된 import문 추가
  src/main/java/com/example/pladialmserver/booking/dto/response/OfficeBookingDetailRes.java
Labels: 🪧 HOTFIX

#36 [PDS-76/feat] 자원 예약 반납 API
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
  src/main/java/com/example/pladialmserver/booking/entity/ResourceBooking.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
Labels: 🔮 Feat

#37 [PDS-47/feat] 자원 목록 조회
  src/main/java/com/example/pladialmserver/booking/entity/ResourceBooking.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepository.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/resouce/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/resouce/dto/response/ResourceRes.java
  src/main/java/com/example/pladialmserver/resouce/entity/Resource.java
  src/main/java/com/example/pladialmserver/resouce/repository/ResourceRepository.java
  src/main/java/com/example/pladialmserver/resouce/service/ResourceService.java
Labels: 🔮 Feat

#38 [PDS-73/feat] 예약 목록 조회(자원) API
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
  src/main/java/com/example/pladialmserver/booking/dto/response/BookingRes.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepository.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
Labels: 🔮 Feat

#39 [PDS-74/feat] 자원 예약 개별 조회 API
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
  src/main/java/com/example/pladialmserver/booking/dto/response/ResourceBookingDetailRes.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/global/utils/DateTimeUtil.java
Labels: 🔮 Feat

#41 [PDS-47/fix] 예외처리 추가, response스웨거 설정 추가
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/resouce/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/resouce/dto/response/ResourceRes.java
  src/main/java/com/example/pladialmserver/resouce/service/ResourceService.java
Labels: ⛑️ Fix

#42 [PDS-74/fix] 자원 예약 개별 조회 자원 Id 추가
  src/main/java/com/example/pladialmserver/booking/dto/response/ResourceBookingDetailRes.java
  src/main/java/com/example/pladialmserver/booking/entity/ResourceBooking.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/resource/dto/request/ResourceReq.java
  src/main/java/com/example/pladialmserver/resource/dto/response/ResourceRes.java
  src/main/java/com/example/pladialmserver/resource/entity/Resource.java
  src/main/java/com/example/pladialmserver/resource/repository/ResourceRepository.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: ⛑️ Fix

#43 [PDS-70/feat] 자원 개별 조회 API
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/resource/dto/response/ResourceDetailRes.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: 🔮 Feat

#44 [PDS-75/fix] 회의실 예약 취소, 자원 예약 취소/반납 API URI 변경
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
Labels: ⛑️ Fix

#45 [PDS-11/fix] response 스웨거 설정
  src/main/java/com/example/pladialmserver/office/controller/OfficeController.java
  src/main/java/com/example/pladialmserver/office/dto/response/OfficeRes.java
Labels: ⛑️ Fix

#48 [PDS-15/hotfix] 예약하기 API 예외처리 에러 해결
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: 🔮 Feat

#49 [PDS-19/fix] 일자별 회의실 예약 현황 조회 예약취소 상태 미반영 처리
  src/main/java/com/example/pladialmserver/booking/repository/officeBooking/OfficeBookingRepository.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: ⛑️ Fix

#50 [PDS-76/fix] 자원 예약 반납 API 반납 일시 추가 저장
  src/main/java/com/example/pladialmserver/booking/entity/ResourceBooking.java
Labels: ⛑️ Fix

#51 [PDS-81/feat] 로그인 리졸버 설정 및 로그인 API
  build.gradle
  src/main/java/com/example/pladialmserver/global/Constants.java
  src/main/java/com/example/pladialmserver/global/config/WebConfig.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/global/resolver/Account.java
  src/main/java/com/example/pladialmserver/global/resolver/LoginResolver.java
  src/main/java/com/example/pladialmserver/global/utils/JwtUtil.java
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
  src/main/java/com/example/pladialmserver/user/dto/TokenDto.java
  src/main/java/com/example/pladialmserver/user/dto/request/LoginReq.java
  src/main/java/com/example/pladialmserver/user/entity/Department.java
  src/main/java/com/example/pladialmserver/user/entity/Position.java
  src/main/java/com/example/pladialmserver/user/entity/User.java
  src/main/java/com/example/pladialmserver/user/repository/UserRepository.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: 🔮 Feat

#47 [PDS-102/feat] 관리자 회의실 예약 목록 조회 API
  src/main/java/com/example/pladialmserver/admin/AdminBookingRes.java
  src/main/java/com/example/pladialmserver/admin/BookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/repository/officeBooking/OfficeBookingRepository.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
Labels: 🔮 Feat

#52 [PDS-71/feat] 자원 월별 예약 현황 조회
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/global/utils/DateTimeUtil.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: 🔮 Feat

#53 [PDS-15/fix] 회의실 예약 API queryDSL 쿼리 오류 수정
  src/main/java/com/example/pladialmserver/booking/repository/officeBooking/OfficeBookingRepositoryImpl.java
Labels: ⛑️ Fix

#55 [PDS-83/feat] 회원정보(이름, 직급) 조회 API
  src/main/java/com/example/pladialmserver/global/config/SwaggerConfig.java
  src/main/java/com/example/pladialmserver/global/utils/JwtUtil.java
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
  src/main/java/com/example/pladialmserver/user/dto/response/UserPositionRes.java
  src/main/java/com/example/pladialmserver/user/entity/Department.java
  src/main/java/com/example/pladialmserver/user/entity/Position.java
  src/main/java/com/example/pladialmserver/user/entity/User.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: 🔮 Feat

#56 [PDS-102/fix] admin도메인 삭제, booking도메인으로 이동
  src/main/java/com/example/pladialmserver/booking/controller/BookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/dto/response/AdminBookingRes.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
Labels: 🪧 HOTFIX

#58 [PDS-81/hotfix] yaml 파일 수정
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: 🪧 HOTFIX

#57 [PDS-72/feat] 자원 예약 API
  src/main/java/com/example/pladialmserver/booking/entity/ResourceBooking.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/resource/dto/request/ResourceReq.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: 🔮 Feat

#54 [PDS-105/feat] 서버간 통신을 위한 feign client 설정
  build.gradle
  src/main/java/com/example/pladialmserver/PladiAlmServerApplication.java
  src/main/java/com/example/pladialmserver/global/feign/dto/UserReq.java
  src/main/java/com/example/pladialmserver/global/feign/event/DeleteUserEvent.java
  src/main/java/com/example/pladialmserver/global/feign/event/UpdateUserEvent.java
  src/main/java/com/example/pladialmserver/global/feign/event/UserEvent.java
  src/main/java/com/example/pladialmserver/global/feign/feignClient/ArchivingServerClient.java
  src/main/java/com/example/pladialmserver/global/feign/handler/ArchivingServerEventHandler.java
  src/main/java/com/example/pladialmserver/global/feign/handler/ArchivingServerEventHandlerImpl.java
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
  src/main/resources/application-dev.yml
Labels: 🎡 Infra, 🔮 Feat

#59 [PDS-108/feat] 관리자 자원 예약 반려 API
  src/main/java/com/example/pladialmserver/booking/controller/BookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/entity/ResourceBooking.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
Labels: 🔮 Feat

#61 [PDS-103/feat] 관리자 자원 예약 허가 API
  src/main/java/com/example/pladialmserver/booking/controller/BookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/entity/ResourceBooking.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
Labels: 🔮 Feat

#60 [PDS-89/feat] 관리자 회의실 상세 내역 조회 API
  src/main/java/com/example/pladialmserver/booking/controller/BookingAdminController.java
Labels: 🔮 Feat

#63 [PDS-109/hotfix] context path 설정
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: 🪧 HOTFIX

#65 [PDS-83/hotfix] 사용자정보 API method 변경
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
Labels: 🪧 HOTFIX

#62 [PDS-106/feat] 관리자 자원 예약 목록 조회
  src/main/java/com/example/pladialmserver/booking/controller/BookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepository.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceAdminController.java
  src/main/java/com/example/pladialmserver/resource/dto/response/AdminResourceRes.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: 🔮 Feat

#64 [PDS-92/feat] 관리자 회의실 예약 반려 API
  src/main/java/com/example/pladialmserver/booking/controller/BookingAdminController.java
Labels: 🔮 Feat

#66 [PDS-82/feat] 레디스 초기 설정 및 로그아웃 API
  build.gradle
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
  src/main/java/com/example/pladialmserver/global/Constants.java
  src/main/java/com/example/pladialmserver/global/config/RedisConfig.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/global/resolver/LoginResolver.java
  src/main/java/com/example/pladialmserver/global/utils/JwtUtil.java
  src/main/java/com/example/pladialmserver/global/utils/RedisUtil.java
  src/main/java/com/example/pladialmserver/office/controller/OfficeController.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
  src/main/resources/application-dev.yml
Labels: 🎡 Infra, 🔮 Feat

#67 [PDS-82/hotfix] 회의실 예약 취소 토큰 적용 파라미터 에러 해결
  src/main/java/com/example/pladialmserver/booking/controller/BookingAdminController.java
Labels: 🪧 HOTFIX

#68 [PDS-33/hotfix] WebConfig Cors 설정 쿠키 추가
  src/main/java/com/example/pladialmserver/global/config/WebConfig.java
Labels: 🪧 HOTFIX

#69 [PDS-33/hotfix] WebConfig Cors 설정 addAllowedOrigin 에러 해결
  src/main/java/com/example/pladialmserver/global/config/WebConfig.java
Labels: 🪧 HOTFIX

#71 [PDS-112/feat] 관리자 자원 예약 반납 API
  src/main/java/com/example/pladialmserver/booking/controller/BookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
Labels: 🔮 Feat

#70 [PDS-111/feat] 관리자 자원 예약 개별 조회 API
  src/main/java/com/example/pladialmserver/booking/controller/BookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
  src/main/java/com/example/pladialmserver/global/config/WebConfig.java
Labels: 🔮 Feat

#72 [PDS-113] 로드밸런서 health check controller
  src/main/java/com/example/pladialmserver/PladiAlmServerApplication.java
  src/main/java/com/example/pladialmserver/global/controller/HealthCheckController.java
  src/main/resources/application-dev.yml
Labels: 🪧 HOTFIX

#73 [PDS-114] 스웨거 설명 담당자 추가
  src/main/java/com/example/pladialmserver/booking/controller/BookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/office/controller/OfficeController.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceAdminController.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: 🔮 Feat

#74 [PDS-82/hotfix] bearer token replace -> substring 으로 함수 변경
  src/main/java/com/example/pladialmserver/global/resolver/LoginResolver.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: 🪧 HOTFIX

#75 [PDS-89/hotfix] 관리자 회의실 상세 조회 권한 수정
  src/main/java/com/example/pladialmserver/booking/controller/BookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
Labels: 🪧 HOTFIX

#76 [PDS-89/hotfix] 관리자 자원 예약 목록 조회 컨트롤러 이전
  src/main/java/com/example/pladialmserver/booking/controller/BookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceAdminController.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: 🪧 HOTFIX

#78 [PDS-92/fix] 관리자 리졸버 적용, 관리자 회의실 반려 서비스 로직 수정
  src/main/java/com/example/pladialmserver/booking/controller/BookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
Labels: ⛑️ Fix

#79 [PDS-89/hotfix] 관리자 자원, 회의실 예약목록 조회 res변경
  src/main/java/com/example/pladialmserver/booking/controller/BookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/dto/response/AdminBookingRes.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
  src/main/java/com/example/pladialmserver/resource/dto/response/AdminResourceRes.java
Labels: 🪧 HOTFIX

#77 [PDS-113] update github-action.yml
  .github/workflows/github-action.yml
Labels: 🔮 Feat

#80 [PDS-97/feat] 직원 등록 API
  build.gradle
  src/main/java/com/example/pladialmserver/PladiAlmServerApplication.java
  src/main/java/com/example/pladialmserver/booking/controller/BookingAdminController.java
  src/main/java/com/example/pladialmserver/global/config/WebConfig.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/user/controller/AdminUserController.java
  src/main/java/com/example/pladialmserver/user/dto/request/CreateUserReq.java
  src/main/java/com/example/pladialmserver/user/entity/Role.java
  src/main/java/com/example/pladialmserver/user/entity/User.java
  src/main/java/com/example/pladialmserver/user/repository/DepartmentRepository.java
  src/main/java/com/example/pladialmserver/user/repository/PositionRepository.java
  src/main/java/com/example/pladialmserver/user/repository/UserRepository.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: 🔮 Feat

#83 [PDS-121/Feat] 자원 카테고리 api 생성
  src/main/java/com/example/pladialmserver/resource/controller/ResourceAdminController.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/resource/dto/response/AdminResourceCategoryRes.java
  src/main/java/com/example/pladialmserver/resource/entity/ResourceCategory.java
  src/main/java/com/example/pladialmserver/resource/repository/ResourceCategoryRepository.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: 🔮 Feat

#81 [PDS-115/feat] 부서 및 직책 리스트 API
  src/main/java/com/example/pladialmserver/user/controller/AdminUserController.java
  src/main/java/com/example/pladialmserver/user/dto/response/CompanyRankListRes.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: 🔮 Feat

#85 [PDS-122/feat] 직원 수정 API
  src/main/java/com/example/pladialmserver/user/controller/AdminUserController.java
  src/main/java/com/example/pladialmserver/user/dto/request/UpdateUserReq.java
  src/main/java/com/example/pladialmserver/user/entity/User.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: 🔮 Feat

#87 [PDS-116/feat] 관리자 자원 추가 API
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceAdminController.java
  src/main/java/com/example/pladialmserver/resource/dto/request/CreateResourceReq.java
  src/main/java/com/example/pladialmserver/resource/entity/Resource.java
  src/main/java/com/example/pladialmserver/resource/repository/ResourceCategoryRepository.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: 🔮 Feat

#90 [PDS-63/fix] 검색어 없을때 전체 조회 가능하게 변경
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: ⛑️ Fix

#88 [PDS-98/feat] 직원 탈퇴 API
  src/main/java/com/example/pladialmserver/PladiAlmServerApplication.java
  src/main/java/com/example/pladialmserver/booking/repository/officeBooking/OfficeBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/officeBooking/OfficeBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/global/entityListener/UserEntityListener.java
  src/main/java/com/example/pladialmserver/global/utils/BeanUtil.java
  src/main/java/com/example/pladialmserver/user/controller/AdminUserController.java
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
  src/main/java/com/example/pladialmserver/user/entity/User.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: 🔮 Feat

#92 [PDS-116/hotfix] 충돌로 인한 import문 재추가
  src/main/java/com/example/pladialmserver/resource/controller/ResourceAdminController.java
Labels: 🪧 HOTFIX

#93 [PDS-11/feat] 회의실 목록 조회 시설 검색 기능 추가
  src/main/java/com/example/pladialmserver/booking/repository/officeBooking/OfficeBookingRepository.java
  src/main/java/com/example/pladialmserver/office/controller/OfficeController.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeRepository.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: 🔮 Feat

#94 [PDS-126/feat] 자원 예약 상태 변경 스케줄링
  src/main/java/com/example/pladialmserver/booking/entity/ResourceBooking.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepository.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
Labels: 🔮 Feat

#96 [PDS-125/feat] 토큰 재발급 API
  src/main/java/com/example/pladialmserver/global/resolver/LoginResolver.java
  src/main/java/com/example/pladialmserver/global/utils/JwtUtil.java
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
  src/main/java/com/example/pladialmserver/user/dto/TokenDto.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: 🔮 Feat

#95 [PDS-67/feat] 자원별로 이전 예약/반납 이력들을 조회한다.
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepository.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceAdminController.java
  src/main/java/com/example/pladialmserver/resource/dto/response/AdminResourcesDetailsRes.java
  src/main/java/com/example/pladialmserver/resource/dto/response/ResourcesList.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: 🔮 Feat

#97 [PDS-108/fix] 자원 예약 반려 예약중 상태에서도 가능하도록 수정
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
Labels: ⛑️ Fix

#99 [PDS-15/hotfix] 회의실 예약 API 상태 추가 쿼리 변경
  src/main/java/com/example/pladialmserver/booking/repository/officeBooking/OfficeBookingRepositoryImpl.java
Labels: 🪧 HOTFIX

#100 [PDS-108/hotfix] 자원 예약 반려 사용완료, 예약 취소인 경우 불가능하게 설정
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
Labels: 🪧 HOTFIX

#101 [PDS-88/hotfix] 자원 예약 목록 조회 에러 수정
  src/main/java/com/example/pladialmserver/resource/repository/ResourceRepository.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: 🪧 HOTFIX

#103 [PDS-15/fix] 회의실 예약 현재보다 과거 시간로 등록하는 경우 예외처리 추가
  src/main/java/com/example/pladialmserver/global/utils/DateTimeUtil.java
  src/main/java/com/example/pladialmserver/office/controller/OfficeController.java
Labels: ⛑️ Fix

#104 [PDS-59/feat] 관리자 회의실 추가 api 기능구현
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/office/controller/OfficeAdminController.java
  src/main/java/com/example/pladialmserver/office/entity/Office.java
  src/main/java/com/example/pladialmserver/office/entity/OfficeFacility.java
  src/main/java/com/example/pladialmserver/office/repository/FacilityRepository.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeFacilityRepository.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
  src/main/java/com/example/pladialmserver/resource/dto/request/CreateOfficeReq.java
Labels: 🔮 Feat

#105 [PDS-86/feat] 관리자 회의실 수정 api 기능구현
  src/main/java/com/example/pladialmserver/office/controller/OfficeAdminController.java
  src/main/java/com/example/pladialmserver/office/entity/Office.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeFacilityRepository.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
  src/main/java/com/example/pladialmserver/resource/dto/request/CreateOfficeReq.java
Labels: 🔮 Feat

#106 [PDS-128/feat] 이메일 인증번호 전송 API
  build.gradle
  src/main/java/com/example/pladialmserver/global/config/EmailConfig.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/global/utils/EmailUtil.java
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
  src/main/java/com/example/pladialmserver/user/dto/request/VerifyEmailReq.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
  src/main/resources/application-dev.yml
Labels: 🔮 Feat

#107 [PDS-61/feat] 관리자 회의실 삭제 API기능구현
  src/main/java/com/example/pladialmserver/booking/repository/officeBooking/OfficeBookingRepository.java
  src/main/java/com/example/pladialmserver/global/entity/BookingStatus.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/office/controller/OfficeAdminController.java
  src/main/java/com/example/pladialmserver/office/dto/response/BookedTimeRes.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: 🔮 Feat

#108 [PDS-129/feat] 이메일 인증코드 확인 API
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/global/utils/EmailUtil.java
  src/main/java/com/example/pladialmserver/global/utils/JwtUtil.java
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
  src/main/java/com/example/pladialmserver/user/dto/request/CheckEmailCodeReq.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: 🔮 Feat

#109 [PDS-66/feat] 관리자 회의실별 예약 이력 조회 api
  src/main/java/com/example/pladialmserver/booking/repository/officeBooking/OfficeBookingRepository.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
  src/main/java/com/example/pladialmserver/office/controller/OfficeAdminController.java
  src/main/java/com/example/pladialmserver/office/dto/response/AdminOfficesDetailsRes.java
  src/main/java/com/example/pladialmserver/office/dto/response/OfficesList.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: 🔮 Feat

#112 [PDS-132/fix] 관리자 장비 추가 & 삭제 API 수정
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceAdminController.java
  src/main/java/com/example/pladialmserver/resource/dto/request/CreateResourceReq.java
  src/main/java/com/example/pladialmserver/resource/entity/Resource.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
  src/main/java/com/example/pladialmserver/user/repository/user/UserRepository.java
Labels: ⛑️ Fix

#113 [PDS-133/fix] 채은 생성 API 기획 관련 모든 오류 수정
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/global/resolver/LoginResolver.java
  src/main/java/com/example/pladialmserver/user/controller/AdminUserController.java
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
  src/main/java/com/example/pladialmserver/user/dto/request/CreateUserReq.java
  src/main/java/com/example/pladialmserver/user/dto/request/UpdateUserReq.java
  src/main/java/com/example/pladialmserver/user/dto/response/CompanyRankListRes.java
  src/main/java/com/example/pladialmserver/user/dto/response/DepartmentListDto.java
  src/main/java/com/example/pladialmserver/user/dto/response/UserNameRes.java
  src/main/java/com/example/pladialmserver/user/dto/response/UserRes.java
  src/main/java/com/example/pladialmserver/user/entity/Role.java
  src/main/java/com/example/pladialmserver/user/entity/User.java
  src/main/java/com/example/pladialmserver/user/repository/DepartmentRepository.java
  src/main/java/com/example/pladialmserver/user/repository/PositionRepository.java
  src/main/java/com/example/pladialmserver/user/repository/user/UserRepository.java
  src/main/java/com/example/pladialmserver/user/repository/user/UserRepositoryImpl.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: ⛑️ Fix

#114 [PDS-132/fix] 1차 데모 후 기존 API 기획 수정 반영
  src/main/java/com/example/pladialmserver/booking/controller/BookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/controller/BookingController.java
  src/main/java/com/example/pladialmserver/booking/dto/response/BookingRes.java
  src/main/java/com/example/pladialmserver/booking/dto/response/OfficeBookingDetailRes.java
  src/main/java/com/example/pladialmserver/booking/dto/response/ResourceBookingDetailRes.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/office/controller/OfficeController.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceAdminController.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/resource/dto/response/AdminResourceCategoryRes.java
  src/main/java/com/example/pladialmserver/resource/dto/response/AdminResourcesRes.java
  src/main/java/com/example/pladialmserver/resource/dto/response/ResourceDetailRes.java
  src/main/java/com/example/pladialmserver/resource/repository/ResourceCategoryRepository.java
  src/main/java/com/example/pladialmserver/resource/repository/ResourceRepository.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: ⛑️ Fix

#115 [PDS-133/fix] 휴대폰번호 정규표현식 에러 수정
  src/main/java/com/example/pladialmserver/user/dto/request/CreateUserReq.java
  src/main/java/com/example/pladialmserver/user/dto/request/UpdateUserReq.java
Labels: ⛑️ Fix

#116 [PDS-116/feat] 관리자 장비관리책임자 리스트 API
  src/main/java/com/example/pladialmserver/resource/controller/ResourceAdminController.java
  src/main/java/com/example/pladialmserver/resource/dto/response/AdminResponsibilityListRes.java
  src/main/java/com/example/pladialmserver/resource/dto/response/AdminResponsibilityRes.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
  src/main/java/com/example/pladialmserver/user/repository/user/UserCustom.java
  src/main/java/com/example/pladialmserver/user/repository/user/UserRepositoryImpl.java
Labels: 🔮 Feat

#117 [PDS-134/fix] 1차 데모 후 기존 API 기획 수정 반영
  src/main/java/com/example/pladialmserver/booking/controller/BookingAdminController.java
  src/main/java/com/example/pladialmserver/booking/dto/response/AdminBookingRes.java
  src/main/java/com/example/pladialmserver/booking/service/BookingService.java
  src/main/java/com/example/pladialmserver/office/dto/response/OfficesList.java
  src/main/java/com/example/pladialmserver/office/entity/Office.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeRepository.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceAdminController.java
  src/main/java/com/example/pladialmserver/resource/dto/response/AdminResourceRes.java
  src/main/java/com/example/pladialmserver/resource/dto/response/AdminResourcesDetailsRes.java
  src/main/java/com/example/pladialmserver/resource/dto/response/ResourcesList.java
Labels: ⛑️ Fix

#119 [PDS-88] 관리자 장비 목록 조회 키워드 유무 따른 로직 수정
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: 🪧 HOTFIX

#120 [PDS-116/hotfix] 관리자 장비 추가 long validation 적용
  src/main/java/com/example/pladialmserver/resource/dto/request/CreateResourceReq.java
Labels: 🪧 HOTFIX

#121 [PDS-116/fix] 관리책임자 리스트 API URI 수정
  src/main/java/com/example/pladialmserver/resource/controller/ResourceAdminController.java
  src/main/java/com/example/pladialmserver/resource/dto/response/AdminResponsibilityListRes.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
  src/main/java/com/example/pladialmserver/user/dto/request/CreateUserReq.java
  src/main/java/com/example/pladialmserver/user/dto/request/ResponsibilityListRes.java
  src/main/java/com/example/pladialmserver/user/dto/request/ResponsibilityRes.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: ⛑️ Fix

#122 [PDS-96/fix] 직원 계정 목록 조회 API 부서 필터링 추가
  src/main/java/com/example/pladialmserver/user/controller/AdminUserController.java
  src/main/java/com/example/pladialmserver/user/repository/user/UserCustom.java
  src/main/java/com/example/pladialmserver/user/repository/user/UserRepositoryImpl.java
  src/main/java/com/example/pladialmserver/user/service/UserService.java
Labels: ⛑️ Fix

#123 [PDS-91/hotfix] 관리자 장비별 예약 이력 조회 url수정
  src/main/java/com/example/pladialmserver/resource/controller/ResourceAdminController.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/resource/dto/response/ResourceRes.java
Labels: 🪧 HOTFIX

#124 [PDS-138/feat] 관리자 장비 활성화/비활성화
  src/main/java/com/example/pladialmserver/resource/controller/ResourceAdminController.java
  src/main/java/com/example/pladialmserver/resource/entity/Resource.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: 🔮 Feat

#125 [PDS-116/fix] 관리 책임자 리스트 API URI 수정
  src/main/java/com/example/pladialmserver/user/controller/UserController.java
Labels: ⛑️ Fix

#126 [PDS-70/hotfix] 장비 개별 조회 res 책임자Id 추가
  src/main/java/com/example/pladialmserver/resource/dto/response/ResourceDetailRes.java
Labels: 🪧 HOTFIX

#127 [PDS-117/hotfix] 관리자 장비 수정 시, imgUrl끼리 비교하도록 수정
  src/main/java/com/example/pladialmserver/resource/entity/Resource.java
Labels: 🪧 HOTFIX

#128 [PDS-140/feat] 관리자 회의실을 비활성화/활성화 api
  src/main/java/com/example/pladialmserver/office/controller/OfficeAdminController.java
  src/main/java/com/example/pladialmserver/office/entity/Office.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeRepository.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: 🔮 Feat

#132 [PDS-132/fix] 관리자 장비 목록 조회 시, isEnable 체크 및 동적 쿼리로 변경
  src/main/java/com/example/pladialmserver/resource/controller/ResourceAdminController.java
  src/main/java/com/example/pladialmserver/resource/dto/response/AdminResourcesRes.java
  src/main/java/com/example/pladialmserver/resource/repository/ResourceCustom.java
  src/main/java/com/example/pladialmserver/resource/repository/ResourceRepository.java
  src/main/java/com/example/pladialmserver/resource/repository/ResourceRepositoryImpl.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: ⛑️ Fix, 🧵 Refactor

#133 [PDS-128/feat] 이메일 전송 화면 생성
  build.gradle
  src/main/java/com/example/pladialmserver/global/utils/EmailUtil.java
  src/main/java/com/example/pladialmserver/global/utils/JwtUtil.java
  src/main/resources/static/img/imgLogo.svg
  src/main/resources/static/img/imgNameLogo.svg
  src/main/resources/templates/email.html
Labels: ⛑️ Fix, 🔮 Feat

#134 [PDS-71/fix] 장비 월별 예약 현황 조회(날짜+시간)
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/global/utils/DateTimeUtil.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceController.java
Labels: ⛑️ Fix

#135 [PDS-128/fix] 이메일 전송 이미지 에러 해결 (지메일 포함)
  src/main/resources/static/img/imgLogo.svg
  src/main/resources/static/img/imgNameLogo.svg
  src/main/resources/templates/email.html
Labels: ⛑️ Fix

#136 [PDS-143/feat] 회의실 목록 조회 isEnable,isActive 처리
  src/main/java/com/example/pladialmserver/booking/repository/officeBooking/OfficeBookingRepository.java
  src/main/java/com/example/pladialmserver/booking/repository/officeBooking/OfficeBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/office/dto/response/OfficeRes.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeCustom.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeRepository.java
  src/main/java/com/example/pladialmserver/office/repository/OfficeRepositoryImpl.java
  src/main/java/com/example/pladialmserver/office/service/OfficeService.java
Labels: 🔮 Feat

#137 [PDS-145/feat] 장비 isEnable, isActive 적용
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepository.java
  src/main/java/com/example/pladialmserver/resource/repository/ResourceRepository.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: 🔮 Feat

#129 [PDS-55/feat] 비품 등록 API
  src/main/java/com/example/pladialmserver/equipment/controller/EquipmentController.java
  src/main/java/com/example/pladialmserver/equipment/dto/request/RegisterEquipmentReq.java
  src/main/java/com/example/pladialmserver/equipment/entity/Equipment.java
  src/main/java/com/example/pladialmserver/equipment/entity/EquipmentCategory.java
  src/main/java/com/example/pladialmserver/equipment/repository/EquipmentCategoryRepository.java
  src/main/java/com/example/pladialmserver/equipment/repository/EquipmentRepository.java
  src/main/java/com/example/pladialmserver/equipment/service/EquipmentService.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
Labels: 🔮 Feat

#138 [PDS-72/fix] 장비 예약 날짜+시간 적용, request 바인딩 수정
  src/main/java/com/example/pladialmserver/booking/entity/ResourceBooking.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/global/Constants.java
  src/main/java/com/example/pladialmserver/global/exception/BaseResponseCode.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/resource/dto/request/ResourceReq.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: ⛑️ Fix

#139 [PDS-142/feat] 비품 삭제 API 기능구현
  src/main/java/com/example/pladialmserver/equipment/controller/EquipmentController.java
  src/main/java/com/example/pladialmserver/equipment/entity/Equipment.java
  src/main/java/com/example/pladialmserver/equipment/service/EquipmentService.java
Labels: 🔮 Feat

#140 [PDS-149/feat] 해당 날짜의 장비 예약 내역 조회
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/resource/dto/response/ResourceBookingRes.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: 🔮 Feat

#141 [PDS-71/fix] 장비 예약 현황 조회에 특정 날짜 요청시 가장 가까운 예약 날짜 반환
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: ⛑️ Fix

#142 [PDS-147/feat] 차량 목록 조회 API
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingCustom.java
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingRepository.java
  src/main/java/com/example/pladialmserver/booking/repository/carBooking/CarBookingRepositoryImpl.java
  src/main/java/com/example/pladialmserver/car/controller/CarController.java
  src/main/java/com/example/pladialmserver/car/dto/CarRes.java
  src/main/java/com/example/pladialmserver/car/repository/CarCustom.java
  src/main/java/com/example/pladialmserver/car/repository/CarRepository.java
  src/main/java/com/example/pladialmserver/car/repository/CarRepositoryImpl.java
  src/main/java/com/example/pladialmserver/car/service/CarService.java
Labels: 🔮 Feat

#143 [PDS-88/fix] 장비 목록 조회 localdate타입에서 localdatetime타입으로 수정
  src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepository.java
  src/main/java/com/example/pladialmserver/resource/controller/ResourceController.java
  src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
Labels: ⛑️ Fix

#144 [PDS-142/feat] 비품 삭제 API @SQLDelete 처리
  src/main/java/com/example/pladialmserver/equipment/entity/Equipment.java
  src/main/java/com/example/pladialmserver/equipment/service/EquipmentService.java
Labels: 🔮 Feat
